config/routes.rb
Proto3::Application.routes.draw do  
  
	
  
	get "site/index"
  	get "site/about"
  	get "site/help"
   	get "site/contact"
  
  root :to => "site#index"
  match 'about' => "site#about"
  match 'help' => "site#help"
  match 'contact' => "site#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def index
  	@title = "Welcome"
  end

  def about
  	@title = "About Alterego"
  end

  def help
  	@title = "Alterego Help"
  end
  
  def contact
  	@title = "Contact Us.....NOT"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Alterego (Prototype 3) | <%= @title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="whole_page">
      	<div id="header">Alterego</div>
      	<div id="nav">
			<%= link_to_unless_current "Home", root_path%>
			<%= link_to_unless_current "About", about_path%>
			<%= link_to_unless_current "Help", help_path%>
			<%= link_to_unless_current "Contact", contact_path%>
		</div>
      	<div id="content">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/site/about.html.erb
<h1>About Us</h1>
    <p>Alterego is a social networking website for artists and those who are interested in Arts.</p>
  

app/views/site/help.html.erb
<h1>Help</h1>
<p>This page will contain instructions and a frequently asked questions list.</p>
 

app/views/site/index.html.erb
<h1>Welcome to Alterego!</h1>
    <p>This is going to be the best artsite ever!</p>